name: Release MDFriday Theme

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"
                  
                  gh release create "$tag" \
                    --title="$tag" \
                    --draft \
                    $(find . -type f ! -path "./exampleSite/*" ! -path "./.*" ! -path "./images/*" ! -name "command.sh")
